// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamFinder.API.Data;

#nullable disable

namespace TeamFinderApiv1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamFinder.API.Models.Juego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("TeamFinder.API.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioQueDaLikeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRecibeLikeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioQueDaLikeId");

                    b.HasIndex("UsuarioRecibeLikeId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("TeamFinder.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TeamFinder.API.Models.UsuarioJuego", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("JuegoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "JuegoId");

                    b.HasIndex("JuegoId");

                    b.ToTable("UsuarioJuegos");
                });

            modelBuilder.Entity("TeamFinder.API.Models.Like", b =>
                {
                    b.HasOne("TeamFinder.API.Models.Usuario", "UsuarioQueDaLike")
                        .WithMany("LikesDados")
                        .HasForeignKey("UsuarioQueDaLikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamFinder.API.Models.Usuario", "UsuarioRecibeLike")
                        .WithMany("LikesRecibidos")
                        .HasForeignKey("UsuarioRecibeLikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioQueDaLike");

                    b.Navigation("UsuarioRecibeLike");
                });

            modelBuilder.Entity("TeamFinder.API.Models.UsuarioJuego", b =>
                {
                    b.HasOne("TeamFinder.API.Models.Juego", "Juego")
                        .WithMany("Jugadores")
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamFinder.API.Models.Usuario", "Usuario")
                        .WithMany("JuegosFavoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Juego");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TeamFinder.API.Models.Juego", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("TeamFinder.API.Models.Usuario", b =>
                {
                    b.Navigation("JuegosFavoritos");

                    b.Navigation("LikesDados");

                    b.Navigation("LikesRecibidos");
                });
#pragma warning restore 612, 618
        }
    }
}
